#!/usr/bin/env python3
"""Document 2 of four — The Shape of Insulin.

The subject is the amount of insulin delivered: in a five-minute bin, across a
day, and over the window. NOT the basal/bolus accounting question — how a dose
is labelled is a forecast convention, and describing the signal by its labels
describes the dosing strategy instead of the insulin (Pete, 2026-09-16).

Every number in the prose is regenerated by claims.py and delivery.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import page

OUT = page.OUT
TITLE = "The Shape of Insulin"
FILENAME = "insulin.html"


BODY = r"""
<div class="wrap">

<h1>The shape of insulin</h1>
<p class="lede">The same 159 people, from the delivery side. How much insulin
arrives in five minutes, how much across a day, and how little either of those
holds still.</p>

<section>
<p class="eyebrow">What this is</p>
<div class="col">
<p>A companion to <a href="https://claude.ai/code/artifact/6b061d95-1172-41a8-b048-1a567e2c533c">The
Shape of Glucose</a>, on the same cohort and window: 159 people with type 1
diabetes on an automated insulin-delivery system of the Loop family, each with
full dose, carbohydrate and therapy streams, referred to by alias. That document
describes the controlled variable. This one describes the actuator.</p>
<p><strong>Delivery</strong> means units reaching the body in a five-minute bin
— the effective basal rate over that bin plus whatever bolus landed in it.
Whether a given unit was called basal or bolus is not used: that label is a
forecast convention and a property of the dosing strategy, not of the insulin.
Where the effect of that insulin matters rather than its amount, the quantity is
<strong>activity</strong>: delivery convolved with the insulin model's curve, in
mg/dL of BG-lowering per five minutes.</p>
</div>

<div class="ledger">
  <div class="cell"><div class="k">A bin that delivers anything</div><div class="v">0.11</div>
    <div class="n">units, median. The 99th percentile is 1.6 U; the largest single bin in the cohort is 47 U.</div></div>
  <div class="cell"><div class="k">Bins delivering nothing</div><div class="v">33%</div>
    <div class="n">Median share; range 2–65%. A third of the time the pump is delivering zero.</div></div>
  <div class="cell"><div class="k">Arrives in the busiest 1% of bins</div><div class="v">25%</div>
    <div class="n">Of all insulin. Range 7–59%, and the same for both dosing strategies.</div></div>
  <div class="cell"><div class="k">Total daily dose</div><div class="v">42</div>
    <div class="n">units, median; 9 to 184 across people.</div></div>
  <div class="cell"><div class="k">Day-to-day variation in that total</div><div class="v">20%</div>
    <div class="n">Within one person, coefficient of variation. Range 9–45%.</div></div>
  <div class="cell"><div class="k">Yesterday predicts today at</div><div class="v">0.21</div>
    <div class="n">Correlation of consecutive daily totals. Essentially no weekly cycle either.</div></div>
  <div class="cell"><div class="k">Rapid / ultra-rapid / unrecorded</div><div class="v">52 / 20 / 87</div>
    <div class="n">People, by recorded insulin brand. No delivery statistic separates the first two.</div></div>
</div>
</section>

<hr>

<section>
<p class="eyebrow">Fig 25 · Five minutes</p>
<h2>Delivery is sparse, tiny and bursty</h2>
<div class="col">
<p>At the resolution the controller actually works at, insulin is a nearly-empty
signal. <strong>A third of five-minute bins deliver nothing at all</strong> —
median 33%, and between 19% and 45% for the middle 80% of people, which is the
automation zero-temping or suspending rather than any malfunction. When a bin
does deliver, it delivers very little: a median of
<strong>0.11&nbsp;units</strong>, with the 99th percentile at 1.6&nbsp;U.</p>
<p>The far tail is a different object. The largest single bin anywhere in the
cohort is <strong>47&nbsp;units</strong>, and the distribution of bin sizes runs
over three orders of magnitude. So the signal is not "a small steady trickle
with occasional boluses" so much as a long run of near-nothing punctuated by
events three orders of magnitude larger.</p>
<div class="read"><p><strong>A quarter of all the insulin a person receives
arrives in the busiest 1% of their bins</strong> — median 25%, range 7% to 59%.
That concentration is <em>not</em> an artefact of how doses are labelled: it is
25% for temp-basal users and 26% for automatic-bolus users. However the
automation is configured to deliver, the insulin arrives in bursts.</p></div>
<h3>The day has one strong feature, and it is night</h3>
<p>Averaged by hour of the <em>local</em> day, delivery is flat and low from
midnight to about 07:00 — <strong>0.72 of the daily mean</strong> — then rises
over an hour or two to a broad plateau of <strong>1.15</strong> that lasts until
late evening. Per person the day/night ratio is a median
<strong>1.65&times;</strong>, with the middle 80% between 1.20 and 2.46.
There is no sharp peak hour: the structure is a night block and a day block,
which is what meal-driven delivery on top of a flatter basal requirement looks
like.</p>
</div>
<figure><img alt="Four panels on five-minute delivery: the size distribution of a non-zero bin, the share of bins delivering nothing, the share of insulin in the busiest 1% of bins, and the local time-of-day profile" src="{{FIG:25_delivery}}">
<figcaption><b>25</b> · Top left, the size of a bin that delivers anything, on a log axis. Top right and bottom left, the share of bins delivering nothing and the share of all insulin arriving in the busiest 1% of bins — one point per person, with a density behind. Bottom right, delivery by hour of the local day as a multiple of each person's own daily mean; the black line is the cohort median and the shaded block is midnight to 06:00.</figcaption></figure>
</section>

<hr>

<section>
<p class="eyebrow">Fig 26 · The day, and the window</p>
<h2>The daily total is a trait; the daily total is also never the same twice</h2>
<div class="col">
<p>Summed over a day, delivery is the familiar quantity: a median total daily
dose of <strong>42&nbsp;units</strong>, spanning 9 to 184 across people. Where
it gets interesting is what happens to it from one day to the next.</p>
<p><strong>The same person's daily total varies by 20% around their own
mean</strong> — the middle 80% of people between 15% and 28%, and one person at
45%. Put in units, a typical person taking 42&nbsp;U a day is routinely taking
34 on one day and 50 on another. And that variation is close to
<em>unpredictable</em> from the recent past: consecutive daily totals correlate
at only <strong>0.21</strong>, and at a week's lag the correlation is 0.05, so
there is no weekly rhythm either.</p>
<div class="read"><p>Those two facts sit together oddly and both are true. Over
weekly blocks the daily total is one of the most stable features measured
anywhere in this study — intraclass correlation <strong>0.94</strong>, meaning
almost all of its variance is between people rather than within them. Over
consecutive days it is close to noise. <strong>A person's insulin requirement is
a firm property of them and a poor prediction of their tomorrow.</strong></p></div>
<h3>Over four months, most people hold level</h3>
<p>Fitting each person's daily totals against date gives a drift of median
<strong>+0.3% per 30 days</strong> — the cohort as a whole is flat, and 83 of
156 are rising, which is a coin toss. But the spread matters more than the
centre: the middle 80% run from &minus;4.6% to +6.7% per 30 days, and
<strong>41 of the 156 move by more than 5% per 30 days</strong> in one direction
or the other. Roughly a quarter of people are on a trajectory that would change
their requirement by a fifth over a year, in a cohort whose average requirement
is not moving at all.</p>
</div>
<figure><img alt="Three panels: total daily dose across people, within-person day-to-day variation in it, and its drift over the window" src="{{FIG:26_daily_dose}}">
<figcaption><b>26</b> · One point per person, with a density behind. Left, the median daily total. Middle, how much that total moves from day to day inside one person. Right, its drift across the window, as a percentage of the person's own mean per 30 days.</figcaption></figure>
</section>

<hr>

<section>
<p class="eyebrow">Fig 05 · Delivery becomes activity</p>
<h2>The body is the low-pass filter</h2>
<div class="col">
<p>Everything above describes delivery. What reaches the glucose signal is
delivery convolved with a six-hour activity curve, and the convolution is what
turns the spiky thing into a smooth one. Insulin <em>activity</em> is strongly
autocorrelated for hours where the glucose increment's memory runs out in under
one — so the actuator's own dynamics, not the delivery schedule, set the
timescale the controller has to work on.</p>
<p>Activity rises with glucose, from a median <strong>4.7&nbsp;mg/dL per five
minutes</strong> near a glucose of 100 to <strong>11.8</strong> near 300. That
is the controller working, and it is the single most important fact to carry
into anything conditioned on insulin: <strong>dose responds to glucose, so
glucose conditioned on dose is endogenous.</strong> That question has its own
document.</p>
<p class="foot">The figure's lower-left panel measures a bookkeeping quantity
rather than a property of the insulin: the share of all BG-lowering supplied by
the <em>scheduled</em> basal stream, which a basal-relative forecast books at
zero. It is a median 47%, ranging 23% to 92%. It is reported here because a
forecast written in basal-relative units cannot see that share — not because
the basal/bolus split describes the signal. It mostly describes the strategy:
counted by delivery, "basal share" is 0.24 for automatic-bolus users against
0.73 for temp-basal ones, which is the same therapeutic act under two
names.</p>
</div>
<figure><img alt="Insulin activity distributions in absolute and basal-relative conventions, the scheduled share per person, and activity against glucose" src="{{FIG:05_insulin_activity}}">
<figcaption><b>05</b> · Left, activity as a physiological quantity — every unit in the body. Right, the same stream with the basal schedule subtracted, which is what a basal-relative forecast prices. Lower left, the difference per person, sorted. Lower right, mean activity against glucose.</figcaption></figure>
</section>

<hr>

<section>
<p class="eyebrow">Fig 27 · Formulation</p>
<h2>Which insulin it is changes the curve, and nothing measurable else</h2>
<div class="col">
<p>The activity curve above is chosen from the recorded insulin brand, so the
brand matters twice: it decides how delivery is turned into effect, and it is
the one property of the insulin itself that varies across this cohort. It is
recorded per dose, and readable for <strong>72 of the 159</strong> people:</p>
<ul>
<li><strong>Rapid analogues — 52 people.</strong> Humalog 27, Novolog 22,
Apidra 3.</li>
<li><strong>Ultra-rapid analogues — 20 people.</strong> Fiasp 11, Lyumjev 9.
Four more have Fiasp in a minority of their records behind a dominant rapid
analogue, so 24 have used one at some point in the window.</li>
<li><strong>No brand recorded — 87 people.</strong></li>
</ul>
<div class="read"><p><strong>Tidepool's own acting-type field cannot make this
distinction.</strong> It reads <code>rapid</code> for all 72, Fiasp and Lyumjev
included. The brand string is the only thing in the record that separates a
rapid analogue from an ultra-rapid one, so any analysis that groups by acting
type has silently pooled them.</p></div>
<p>Comparing the two groups on everything this document measures gives
<strong>no detectable difference in any of it</strong>: total daily dose 39 U
against 41 (p&nbsp;=&nbsp;0.64), day-to-day variation in that total 20.4%
against 20.9% (p&nbsp;=&nbsp;0.40), bins delivering nothing 40.0% against 36.6%
(p&nbsp;=&nbsp;0.11), the share arriving in the busiest 1% of bins 27.1% against
23.9% (p&nbsp;=&nbsp;0.20), and the median non-zero bin 0.088&nbsp;U against
0.100 (p&nbsp;=&nbsp;0.48). Drift over the window is the closest to separating,
at +0.4% against &minus;2.0% per 30 days (p&nbsp;=&nbsp;0.10), which at twenty
people is not a finding. (The figure shows 49 of the 52 rapid users: three lack
the thirty complete days a daily total needs.)</p>
<p>That is the expected answer and worth having explicitly. An ultra-rapid
analogue changes <em>when</em> a unit acts, not how much of it a person needs or
how the automation chooses to deliver it — and the amounts are what this
document measures. Where formulation does matter is downstream: it is the
difference between an activity estimate that is correctly timed and one that is
not.</p>
<div class="read"><p><strong>Whether a brand is recorded at all is a property of
the upload path, not of the person.</strong> Every one of the 87 unrecorded
donors uploads through twiist; every one of the 72 with a brand is on Omnipod
(two on Medtronic). So the comparison above lives entirely inside the Omnipod
half of the cohort, and the unrecorded group cannot be read as a third
formulation category — it is a different pump, sensor and dosing strategy. The
two recorded groups are closely matched on all three.</p></div>
<p class="foot">Six people record more than one brand across the window, with
the dominant one covering 81% to 99% of their records; the export assigns a
single curve per person from the most frequent, so a genuine mid-window
formulation change is modelled as if it had not happened.</p>
</div>
<figure><img alt="Six panels comparing total daily dose, its day-to-day variation, zero-delivery bins, burst concentration, median bin size and drift between rapid and ultra-rapid analogue users" src="{{FIG:27_formulation}}">
<figcaption><b>27</b> · One point per person, bar = median, whisker = p10&ndash;p90, for the six delivery statistics this document reports. Rapid analogue users in blue, ultra-rapid in orange. p-values are rank tests.</figcaption></figure>
</section>

<hr>

<section>
<p class="eyebrow">Fig 23 · Trait or state</p>
<h2>Almost nothing on this side moves week to week</h2>
<div class="col">
<p>Split each record into weekly blocks, compute a feature per block, and take
the share of its variance lying <em>between</em> people rather than within one
person over time — the intraclass correlation. Near 1 the feature is a stable
property of the person; near 0 it describes the week. The glucose document runs
this on glucose dynamics, where the answers are mixed. Here they are not.</p>
<p><strong>Everything is a trait.</strong> The lowest ICC on this side —
<strong>0.70</strong>, for the correlation between glucose velocity and insulin
activity — is higher than most of the glucose dynamics. Insulin action and
non-insulin appearance both sit at 0.80, about level with mean glucose. Total
daily dose is 0.94. Carbohydrate announced per day (0.83) and manual boluses per
day (0.86) are stable enough to call announcing a personal habit rather than a
phase.</p>
<p><strong>Settings are near-constants, and that is a finding about
behaviour.</strong> Carb ratio, insulin sensitivity and scheduled basal each
score <strong>0.98</strong>, with week-to-week variation inside a person of a
few per cent. Records show steady editing — people nudge — but the nudges are
small. Whatever moves in a person's glucose from week to week is not, in the
main, their settings moving. The most fixed operational choice of all is the
automated share of boluses, at <strong>0.98</strong>: a dosing strategy, and it
does not drift.</p>
<div class="read"><p>One contrast is worth isolating, because it separates a
configured quantity from a demanded one. The share of a person's total daily
dose that is basal scores <strong>0.95</strong> — it encodes how the pump is set
up. The share of their insulin <em>action</em> coming from the scheduled basal
stream scores only <strong>0.74</strong>, because it moves with how much
correction insulin the week actually needed. Configuration is a trait; what the
week demanded on top of it is not.</p></div>
</div>
<figure><img alt="Intraclass correlation and within-person variation for insulin-side features" src="{{FIG:23_trait_insulin}}">
<figcaption><b>23</b> · ICC with 90% intervals over people (left) and median week-to-week variation as a share of the person's own level (right). Blue = metabolic operating point, orange = how the system is run, gold = settings.</figcaption></figure>

<div class="scroll">
<table>
<thead><tr><th>feature</th><th>ICC</th><th>90% CI</th></tr></thead>
<tbody>
__INSULIN_ROWS__
</tbody>
</table>
</div>
<p class="foot" style="margin-top:12px">Weekly blocks, 157 people. A feature can be a near-perfect trait and still barely vary across the population; the figure's right panel is what ICC hides.</p>
</section>

<section>
<p class="eyebrow">What bounds these numbers</p>
<h2>Limits worth carrying</h2>
<div class="col">
<ul>
<li><strong>Delivery is what the controller believes it delivered.</strong> A
pump or pod that fails mid-dose without telling the phone leaves the record
showing the amount the app thought reached the body. Interruptions the app knows
about — a cancel, a suspend — are in the stream; the ones it does not are
invisible, so every figure here is an upper bound on what actually arrived.</li>
<li><strong>A zero bin is not necessarily a decision.</strong> The third of bins
delivering nothing pools deliberate zero-temping with suspends, pod changes and
periods when the loop was not running. The glucose document's disruption
handling excludes the worst of those from its statistics; the delivery totals
here do not, beyond requiring a day to be near-complete before it carries a
total.</li>
<li><strong>Daily totals need complete days.</strong> A day is only counted if it
has more than 240 of its 288 five-minute bins, and a person only if 30 such days
survive — which is why the delivery figures describe 156 of the 159.</li>
<li><strong>Activity is modelled, not measured.</strong> It is delivery
convolved with a curve chosen from the recorded insulin brand. That brand is
present for 72 people and every one of them gets the matching curve; the other
<strong>87 fall back to a rapid-acting adult curve</strong>, and if any of them
is in fact on an ultra-rapid analogue their activity is placed later than it
really occurred. Amounts are unaffected; anything timing-sensitive carries that
error.</li>
<li><strong>Association, not effect.</strong> Dose responded to state. Nothing
here identifies what would happen if it responded differently.</li>
<li><strong>Only eleven records are individually validated.</strong> Those had
their replay configuration checked against their own field outcomes; the other
148 did not.</li>
</ul>
</div>
</section>

__NAV__

</div>
"""


def insulin_rows() -> str:
    """The insulin-side ICC table, from trait_icc_insulin.csv."""
    import pandas as pd
    NAMES = {
        "cr_mean": "carb ratio", "isf_mean": "insulin sensitivity",
        "basal_sched_mean": "scheduled basal rate",
        "target_lo_mean": "correction-range floor",
        "auto_frac_u": "automated share of boluses",
        "basal_frac": "basal share of total daily dose",
        "tdd": "total daily dose",
        "manual_bolus_day": "manual boluses per day",
        "carb_g_day": "carbohydrate announced per day",
        "iob_net_mean": "insulin on board, basal-relative",
        "ia_abs_mean": "insulin action",
        "ice_abs_mean": "non-insulin appearance",
        "ia_sched_share": "scheduled-basal share of action",
        "corr_v_ia": "velocity-insulin correlation",
    }
    I = pd.read_csv(OUT / "trait_icc_insulin.csv").sort_values("icc", ascending=False)
    return "\n".join(
        f"<tr><td>{NAMES.get(r['feature'], r['feature'])}</td>"
        f"<td>{r['icc']:.2f}</td><td>{r['lo']:.2f}–{r['hi']:.2f}</td></tr>"
        for _, r in I.iterrows())


def build() -> Path:
    body = (BODY.replace("__INSULIN_ROWS__", insulin_rows())
                .replace("__NAV__", page.nav("insulin")))
    return page.build(body, FILENAME, TITLE)


if __name__ == "__main__":
    build()
