#!/usr/bin/env python3
"""Document 4 of four — Counteraction.

Everything insulin did not do, treated as a quantity in its own right rather
than as a residual to be tidied away: how big it is, what shape it has, and the
one thing about it that looks like a finding and is mostly an artefact of how it
is defined.

Every number in the prose is regenerated by claims.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import page

OUT = page.OUT
TITLE = "Counteraction"
FILENAME = "counteraction.html"


BODY = r"""
<div class="wrap">

<h1>Counteraction</h1>
<p class="lede">Glucose velocity plus insulin activity leaves everything
insulin did not do — production, carbohydrate, exercise, error. It is as large
as insulin action, it carries the distribution's awkward shape, and it is
defined as a residual, which bounds what can be claimed about it.</p>

<section>
<p class="eyebrow">What this is</p>
<div class="col">
<p>The last of four documents on the same 159 people. The glucose document
describes the increment, the insulin document the delivery signal, and the
conditioning document what happens when you put them together. This one is
about the term that is left over.</p>
<p><strong>Non-insulin appearance</strong> here means glucose velocity plus
modelled insulin activity, in mg/dL per hour. If insulin is lowering glucose at
80&nbsp;mg/dL per hour and glucose is flat, then something is raising it at
80&nbsp;mg/dL per hour, and that something is what this document is about. Loop
computes a version of the same quantity to drive retrospective correction.</p>
<div class="read"><p><strong>It is a residual, and residuals inherit
everything.</strong> Appearance is not measured; it is <em>defined</em> as
velocity minus the modelled insulin effect. Every error in the insulin model,
every mis-timed dose, and every bit of sensor noise lands in it with the
opposite sign. Read what follows as a description of that residual, which is
what a controller actually sees — not as a physiological measurement of
endogenous glucose production.</p></div>
</div>

<div class="ledger">
  <div class="cell"><div class="k">Mean appearance</div><div class="v">81</div>
    <div class="n">mg/dL per hour, median across people; range 36–178. The same order as insulin action, necessarily.</div></div>
  <div class="cell"><div class="k">Balances insulin action to</div><div class="v">0.6%</div>
    <div class="n">Median over the whole record, worst 8%. An identity check on the pipeline, not a finding.</div></div>
  <div class="cell"><div class="k">Rises with glucose</div><div class="v">0.47</div>
    <div class="n">mg/dL per hour for every mg/dL of glucose. But see below — most of it is not physiology.</div></div>
  <div class="cell"><div class="k">... of which dosing</div><div class="v">84%</div>
    <div class="n">Insulin action's own slope against glucose, which the identity requires appearance to offset.</div></div>
</div>
</section>

<hr>

<section>
<p class="eyebrow">Fig 06 · The non-insulin side</p>
<h2>It is as large as insulin action, and a worse-behaved distribution</h2>
<div class="col">
<p>Appearance is big. Mean values run from <strong>36 to
178&nbsp;mg/dL per hour</strong> across people, median 81 — the same order as
insulin action, which is not a coincidence but an identity: over months the two
must cancel, or glucose would drift without bound. They do, to within
<strong>0.6%</strong> of insulin action at the median and 8% at worst. That is
worth reporting only because it is a check: a pipeline that reconstructed doses
badly, or convolved them with the wrong curve, would fail it.</p>
<p>The distribution is two-sided, unlike insulin activity, and it is the
<em>awkward</em> one. Standardised and plotted against a Laplace, the
increment-with-insulin-added-back is further from straight than the raw
increment is. Whatever gives glucose its heavy tail is on this side of the
ledger. That is the negative result the other three documents converge on:
not the sensor (about 10% of five-minute variance), not the level (a log
over-corrects), not the insulin (removing it makes the fit worse), and not the
nameable states (4% of the squared increment).</p>

<h3>The one apparent finding, and why it mostly is not one</h3>
<p>Appearance <strong>rises</strong> with glucose — about
<strong>0.47&nbsp;mg/dL per hour for every mg/dL</strong>, so roughly
50&nbsp;mg/dL per hour at a glucose of 100 against 150 at a glucose of 300. A
tempting reading is counter-regulation, or absorption concentrated at highs.</p>
<div class="read"><p><strong>84% of that slope is the controller's own
dosing.</strong> Insulin action rises against glucose at 0.39 of the same
units, and the identity then <em>requires</em> appearance to rise by as much to
reproduce the observed velocity. The residual — the part not explained by the
loop dosing harder when glucose is high — is
<strong>0.06&nbsp;mg/dL per hour per mg/dL</strong>, about an eighth of the raw
figure. The apparent dose-response of endogenous appearance to glucose is
mostly the reflection of the dose.</p></div>
<p>This is the same endogeneity that limits the conditioning document, arriving
from the other direction, and it is the reason this quantity needs a
counterfactual rather than a conditional mean. What appearance would have done
had the loop dosed differently is not in this data.</p>
</div>
<figure><img alt="Non-insulin appearance distributions in both conventions, the balance check against insulin action, and appearance against glucose with insulin action beside it" src="{{FIG:06_non_insulin}}">
<figcaption><b>06</b> · Top, appearance in the absolute convention and in the basal-relative one Loop's retrospective correction uses. Lower left, the balance identity — every person on the diagonal. Lower right, mean appearance against glucose, with each person's insulin action dashed beside it: the two rise together, which is the point.</figcaption></figure>
</section>

<section>
<p class="eyebrow">What bounds these numbers</p>
<h2>Limits worth carrying</h2>
<div class="col">
<ul>
<li><strong>Appearance is a residual of a modelled quantity.</strong> It is
velocity minus delivery convolved with an activity curve taken from the
recorded insulin brand, which is absent for 139 of the 159 people. A curve
that is too slow moves appearance earlier and shrinks it; the error does not
average out within a day.</li>
<li><strong>It contains the sensor.</strong> Measurement noise enters velocity
and therefore appearance directly. About 10% of five-minute increment variance
is noise, so the high-frequency content of appearance is partly instrumental.</li>
<li><strong>Its relationship to glucose is dominated by dosing.</strong> Any
conditional statement about appearance given glucose, insulin on board or
carbohydrate on board inherits the controller's response to the same variable.
The decomposition above is the minimum correction; it is not an
identification.</li>
<li><strong>Rescue carbohydrate is in it.</strong> The low tail of appearance
includes deliberate treatment of hypoglycaemia, which is a behavioural response
to the trajectory rather than an exogenous input.</li>
<li><strong>The balance check cannot detect a scale error.</strong> Appearance
matching insulin action to 0.6% follows from the definition over a long window;
it validates dose reconstruction and bookkeeping, not the activity curve.</li>
</ul>
</div>
</section>

__NAV__

</div>
"""


def build() -> Path:
    return page.build(BODY.replace("__NAV__", page.nav("counteraction")),
                      FILENAME, TITLE)


if __name__ == "__main__":
    build()
