#!/usr/bin/env python3
"""Document 2 of four — The Shape of Insulin.

The insulin side as a process in its own right: what its activity stream looks
like, the two incompatible definitions of "basal" and which one a forecast
prices, and how little of any of it moves from week to week. Split out of the
glucose document in 2026-09; that document is now glucose only.

Every number in the prose is regenerated by claims.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import page

OUT = page.OUT
TITLE = "The Shape of Insulin"
FILENAME = "insulin.html"


BODY = r"""
<div class="wrap">

<h1>The shape of insulin</h1>
<p class="lede">The same 159 people, from the delivery side. What insulin
activity looks like as a signal, why "basal share" has two answers that differ
by half, and why almost nothing here changes from one week to the next.</p>

<section>
<p class="eyebrow">What this is</p>
<div class="col">
<p>A companion to <a href="https://claude.ai/code/artifact/6b061d95-1172-41a8-b048-1a567e2c533c">The
Shape of Glucose</a>, on the same cohort and the same window: 159 people with
type 1 diabetes on an automated insulin-delivery system of the Loop family,
each with full dose, carbohydrate and therapy streams, referred to by alias.
The glucose document describes what the controlled variable does. This one
describes the control signal.</p>
<p>Insulin <strong>activity</strong> throughout means BG-lowering per five
minutes — units delivered convolved with the insulin model's activity curve,
expressed in the same mg/dL units as glucose velocity so the two can be
compared directly. It is a <em>modelled</em> quantity, not a measured one, and
the model comes from the recorded insulin brand; see the limits.</p>
</div>

<div class="ledger">
  <div class="cell"><div class="k">Insulin action from scheduled basal</div><div class="v">47%</div>
    <div class="n">Median; range 23–92%. The share of all BG-lowering that a basal-relative forecast books at zero.</div></div>
  <div class="cell"><div class="k">Delivered-basal share, by strategy</div><div class="v">0.24 / 0.73</div>
    <div class="n">Automatic-bolus users against temp-basal users — a gap of 0.49 that is a naming convention, not a difference in therapy.</div></div>
  <div class="cell"><div class="k">Scheduled share, by strategy</div><div class="v">0.43 / 0.50</div>
    <div class="n">The same two groups, counted by schedule instead. A gap of 0.07 — much less strategy-dependent, not free of it.</div></div>
  <div class="cell"><div class="k">Settings stability</div><div class="v">ICC 0.98</div>
    <div class="n">Carb ratio, ISF and scheduled basal, week to week. Near-constants.</div></div>
  <div class="cell"><div class="k">Least stable insulin feature</div><div class="v">ICC 0.70</div>
    <div class="n">The velocity–insulin correlation — still above most of the glucose dynamics.</div></div>
  <div class="cell"><div class="k">Non-insulin appearance</div><div class="v">81</div>
    <div class="n">mg/dL per hour, median; range 36–178. Balances mean insulin action to 0.6%.</div></div>
</div>
</section>

<hr>

<section>
<p class="eyebrow">Fig 05 · The activity stream</p>
<h2>Insulin is slow and smooth where glucose is fast and rough</h2>
<div class="col">
<p>Expressed as BG-lowering per five minutes, insulin activity is a different
kind of signal from glucose velocity. It is strongly autocorrelated for
<em>hours</em> — a six-hour convolution kernel guarantees it — where velocity's
memory runs out in under one. Its distribution is one-sided and smooth: there
is no equivalent of the sharp Laplace peak the increment has, because activity
is an integral of past delivery rather than a difference of a noisy
measurement.</p>
<p>Activity also rises with glucose, from a median <strong>4.7&nbsp;mg/dL per five
minutes</strong> near a glucose of 100 to <strong>11.8</strong> near 300. That is the controller working, and it
is the single most important fact to hold onto when reading anything
conditioned on insulin: <strong>dose responds to glucose, so glucose
conditioned on dose is endogenous.</strong> That question has its own
document.</p>

<h3>"Basal share" has two answers, and the strategy decides which one you got</h3>
<p>The scheduled basal stream — the schedule itself, not temp basals layered on
it — supplies a median <strong>47%</strong> of all BG-lowering delivered,
ranging from 23% to 92%. A basal-relative forecast books that entire stream at
zero, which is why the number matters: it is the share of insulin action that
such a forecast cannot see.</p>
<p>The distinction from <em>delivered</em> basal is not pedantry. The population
splits on how automated insulin arrives — 94 of the 159 run a temp-basal
strategy, where every correction the controller makes is delivered as basal, and
65 an automatic-bolus strategy. Counted by delivery, "basal share" is
<strong>0.24</strong> for the bolus group against <strong>0.73</strong> for the
temp-basal group. That gap of 0.49 is a labelling artefact: the same therapeutic
act is called basal in one group and bolus in the other.</p>
<div class="read"><p>Counted by <em>schedule</em>, the gap shrinks to
<strong>0.07</strong> — 0.43 against 0.50. So the scheduled share is much the
less strategy-dependent of the two definitions, and it is the one to use. It is
not strategy-<em>free</em>, though, so report it by strategy rather than
pooling.</p></div>
</div>
<figure><img alt="Insulin activity distributions in absolute and basal-relative conventions, the scheduled share per person, and activity against glucose" src="{{FIG:05_insulin_activity}}">
<figcaption><b>05</b> · Left, the physiological quantity — every unit in the body. Right, the same stream with the basal schedule subtracted, which is what a basal-relative forecast prices. Lower left, the difference per person, sorted. Lower right, mean activity against glucose.</figcaption></figure>
</section>

<hr>

<section>
<p class="eyebrow">Fig 23 · Trait or state</p>
<h2>The insulin side is stable in a way the glucose side is not</h2>
<div class="col">
<p>Split each record into weekly blocks, compute a feature per block, and take
the share of its variance lying <em>between</em> people rather than within one
person over time — the intraclass correlation, ICC. Near 1 the feature is a
stable property of the person; near 0 it describes the week you happened to
measure. The glucose document runs this on glucose dynamics, where the answers
are mixed. On the insulin side they are not.</p>
<p><strong>Everything here is a trait.</strong> The lowest ICC on the insulin
side — <strong>0.70</strong>, for the correlation between velocity and insulin
activity — is higher than most of the glucose dynamics. Insulin action and
non-insulin appearance both sit at 0.80, about level with mean glucose. Total
daily dose is 0.94. Carbohydrate announced per day (0.83) and manual boluses per
day (0.86) are stable enough to call announcing a personal habit rather than a
phase.</p>
<p><strong>Settings are near-constants, and that is a finding about
behaviour.</strong> Carb ratio, ISF and scheduled basal each score
<strong>0.98</strong>, with week-to-week variation inside a person of a few per
cent. Records show steady editing — people nudge — but the nudges are small.
Whatever moves in a person's glucose from week to week is not, in the main,
their settings moving.</p>
<div class="read"><p>One contrast is worth isolating. The share of a person's
total daily dose that is basal scores <strong>0.95</strong>; the share of their
insulin <em>action</em> coming from the <em>scheduled</em> basal stream scores
only <strong>0.74</strong>. The first is stable because it encodes a choice —
how the pump is configured. The second moves with how much correction insulin
the week actually needed. Configuration is a trait; what the week demanded on
top of it is not.</p></div>
<p>The most fixed operational choice in the data is the automated share of
boluses, at <strong>0.98</strong> — which is what a dosing strategy is. It does
not drift.</p>
</div>
<figure><img alt="Intraclass correlation and within-person variation for insulin-side features" src="{{FIG:23_trait_insulin}}">
<figcaption><b>23</b> · ICC with 90% intervals over people (left) and median week-to-week variation as a share of the person's own level (right). Blue = metabolic operating point, orange = how the system is run, gold = settings.</figcaption></figure>

<div class="scroll">
<table>
<thead><tr><th>feature</th><th>ICC</th><th>90% CI</th></tr></thead>
<tbody>
__INSULIN_ROWS__
</tbody>
</table>
</div>
<p class="foot" style="margin-top:12px">Weekly blocks, 157 people. A feature can be a near-perfect trait and still barely vary across the population; the figure's right panel is what ICC hides.</p>
</section>

<section>
<p class="eyebrow">What bounds these numbers</p>
<h2>Limits worth carrying</h2>
<div class="col">
<ul>
<li><strong>Insulin activity is modelled, not measured.</strong> It is delivery
convolved with an activity curve chosen from the recorded insulin brand.
<strong>139 of the 159</strong> carry the rapid-acting-adult curve, and the
record cannot say which of those chose it and which merely lack a brand; where
the true insulin is faster, their activity is placed later than it really
occurred. Level statistics are unaffected; anything timing-sensitive carries
that error.</li>
<li><strong>Delivery is what the controller believes it delivered.</strong> A
pump or pod that fails mid-dose without telling the phone leaves the record
showing the amount the app believed it delivered. Interruptions the app knows
about — a cancel, a suspend — are in the stream; the ones it does not are
invisible here, so every activity estimate is an upper bound on what reached
the body.</li>
<li><strong>"Basal" is a naming convention before it is a quantity.</strong>
Every comparison of basal share across people has to state which definition it
used and split by dosing strategy, or it is mostly measuring the strategy.</li>
<li><strong>Association, not effect.</strong> Dose responded to state. Nothing
here identifies what would happen if it responded differently.</li>
<li><strong>Only eleven records are individually validated.</strong> Those had
their replay configuration checked against their own field outcomes; the other
148 did not.</li>
</ul>
</div>
</section>

__NAV__

</div>
"""


def insulin_rows() -> str:
    """The insulin-side ICC table, from trait_icc_insulin.csv."""
    import pandas as pd
    NAMES = {
        "cr_mean": "carb ratio", "isf_mean": "insulin sensitivity",
        "basal_sched_mean": "scheduled basal rate",
        "target_lo_mean": "correction-range floor",
        "auto_frac_u": "automated share of boluses",
        "basal_frac": "basal share of total daily dose",
        "tdd": "total daily dose",
        "manual_bolus_day": "manual boluses per day",
        "carb_g_day": "carbohydrate announced per day",
        "iob_net_mean": "insulin on board, basal-relative",
        "ia_abs_mean": "insulin action",
        "ice_abs_mean": "non-insulin appearance",
        "ia_sched_share": "scheduled-basal share of action",
        "corr_v_ia": "velocity-insulin correlation",
    }
    I = pd.read_csv(OUT / "trait_icc_insulin.csv").sort_values("icc", ascending=False)
    return "\n".join(
        f"<tr><td>{NAMES.get(r['feature'], r['feature'])}</td>"
        f"<td>{r['icc']:.2f}</td><td>{r['lo']:.2f}–{r['hi']:.2f}</td></tr>"
        for _, r in I.iterrows())


def build() -> Path:
    body = (BODY.replace("__INSULIN_ROWS__", insulin_rows())
                .replace("__NAV__", page.nav("insulin")))
    return page.build(body, FILENAME, TITLE)


if __name__ == "__main__":
    build()
