#!/usr/bin/env python3
"""Document 3 of four — Glucose Given Insulin.

What happens to the glucose distribution when you condition on the insulin
acting, and why that conditioning cannot be read as an effect. Also the
negative result that bounds the whole programme: named states — clock, carbs
on board, insulin activity — explain almost none of the increment's tail,
while a latent volatility estimate explains four times as much.

Every number in the prose is regenerated by claims.py and modality_kurtosis.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import page

OUT = page.OUT
TITLE = "Glucose Given Insulin"
FILENAME = "conditioning.html"


BODY = r"""
<div class="wrap">

<h1>Glucose given insulin</h1>
<p class="lede">Condition the five-minute increment on how much insulin is
acting and it shifts and widens, exactly as it should. Neither movement is an
effect, and the states we can name turn out to explain almost none of what
makes the distribution hard.</p>

<section>
<p class="eyebrow">What this is</p>
<div class="col">
<p>The third of four documents on the same 159 people.
<a href="https://claude.ai/code/artifact/6b061d95-1172-41a8-b048-1a567e2c533c">The
Shape of Glucose</a> describes the increment unconditionally; the insulin
companion describes the delivery signal. This one puts them together, and its
main result is a warning about doing so.</p>
<div class="read"><p><strong>The conditioning is endogenous, and there is no
way around it in observational data.</strong> The controller doses
<em>because</em> glucose is high or rising. So E[Δglucose | insulin activity]
mixes the thing we want — what insulin does — with the thing that produced the
insulin. Every number on this page is an association measured inside a closed
loop that was already reacting. What insulin <em>would</em> do to a trajectory
needs a counterfactual simulation, not a conditional mean.</p></div>
</div>
</section>

<hr>

<section>
<p class="eyebrow">Fig 12 · Conditioning</p>
<h2>It shifts the centre and widens the spread — by about half an SD</h2>
<div class="col">
<p>Split each person's record into quintiles of insulin activity and look at
the increment inside each. Moving from the lowest quintile to the highest
shifts the mean increment by <strong>&minus;2.64&nbsp;mg/dL per five
minutes</strong> at the median, which is <strong>0.44 of that person's own
increment SD</strong> — a real displacement, and a smaller one than the raw
number suggests until it is scaled by how much the increment moves anyway.</p>
<p>It also <strong>widens</strong> the distribution, by a factor of
<strong>1.45&times;</strong> from bottom quintile to top (middle 80% of people
1.15 to 1.82). High insulin activity is not just a downward push; it is a
noisier regime. A forecast band that scales with insulin activity would be
better specified than one that does not.</p>
<p>The sign is not universal. <strong>Five of the 159 come out with the shift
reversed</strong> — more insulin acting, higher mean increment — which is what
endogeneity looks like in an individual record: those are people whose dosing
tracks their rises so closely that the dose arrives labelled with the rise.</p>

<h3>The timescales do not match</h3>
<p>Insulin activity's autocorrelation runs for <em>hours</em>; the increment's
is gone inside one. Across the whole record the correlation between them is
only <strong>&minus;0.36 to +0.06</strong>, median &minus;0.16. Two signals
this differently scaled do not have a useful instantaneous relationship, which
is the deeper reason a per-step conditional mean is a weak instrument here.</p>

<h3>Removing insulin makes the shape worse, not better</h3>
<p>If insulin were the source of the increment's awkward distribution, then
subtracting its modelled activity off should leave something better behaved. It
does the opposite: the Q-Q plot of velocity-plus-insulin-activity against a
Laplace is <em>further</em> from straight than raw velocity's. Whatever gives
the increment its shape lives on the non-insulin side — which is the fourth
document.</p>
</div>
<figure><img alt="Velocity conditioned on insulin-activity quintile, the shift and spread across people, autocorrelation comparison, and Laplace Q-Q with and without insulin removed" src="{{FIG:12_insulin_joint}}">
<figcaption><b>12</b> · Top left, one person's increment density by insulin-activity quintile. Top middle and right, the mean shift and the spread ratio across all 159. Bottom left, insulin activity's autocorrelation (coloured) against the increment's (grey) — the timescale gap. Bottom middle and right, the increment against a Laplace, raw and with insulin activity added back.</figcaption></figure>
</section>

<hr>

<section>
<p class="eyebrow">Fig 24 · Named states</p>
<h2>The states we can name explain almost none of the tail</h2>
<div class="col">
<p>The increment's fat tail has an obvious candidate explanation: it is a
mixture. Meals, nights, exercise and correction doses are different regimes
with different spreads, and pooling them would produce exactly the sharp peak
and heavy flanks that the unconditional distribution has. If that were true,
dividing each increment by the spread of the state it occurred in would remove
the excess.</p>
<p><strong>It removes nothing.</strong> Label every increment by local time of
day, whether carbohydrate was on board, and which tertile of insulin activity
it sat in — then standardise within those cells. Median excess kurtosis goes
from <strong>2.57 raw to 2.71 conditioned</strong>: no reduction at all. The
same increments divided by a <em>causal volatility estimate</em> — a latent
quantity read off the recent trace, naming nothing — fall to
<strong>1.75</strong>. Measured as variance explained, the named-state cell
accounts for <strong>4%</strong> of the squared increment against the latent
estimate's <strong>16%</strong>.</p>
<div class="read"><p><strong>The fat tail is not where the eating is.</strong>
Excess kurtosis inside each state runs <strong>1.14</strong> daytime with carbs
on board, <strong>3.08</strong> daytime after four hours fasted, and
<strong>4.12</strong> overnight fasted. The calmest, most boring state has the
heaviest tail. This is not compression lows — it holds with the low range
excluded — and it holds among people who announce heavily, for whom
carbs-on-board is a meaningful label.</p></div>
<p>So the mixture generating the tail is <em>latent</em>, not scheduled. A
model that reaches for a circadian term, a meal flag or an insulin-state
indicator to capture it is reaching for the wrong thing; a model that estimates
volatility from the recent trace captures four times as much with no labels at
all.</p>
</div>
<figure><img alt="Three panels: excess kurtosis raw, conditioned on named states, and conditioned on causal volatility; kurtosis within each named state; and variance explained by each" src="{{FIG:24_modality}}">
<figcaption><b>24</b> · One faint line per person between conditions, medians marked. Left, the increment's excess kurtosis raw, standardised within its named state, and standardised by a causal volatility estimate. Middle, kurtosis measured inside each state separately. Right, the share of the squared increment each approach explains.</figcaption></figure>
</section>

<section>
<p class="eyebrow">What bounds these numbers</p>
<h2>Limits worth carrying</h2>
<div class="col">
<ul>
<li><strong>Endogeneity is the whole story, not a caveat.</strong> Dose
responded to glucose. Nothing on this page identifies a causal effect of
insulin, and the sign reversal in five people is the visible edge of that
problem rather than an anomaly.</li>
<li><strong>Insulin activity is modelled.</strong> Delivery convolved with a
curve chosen from the recorded brand, which is absent for 139 of the 159. A
mis-timed activity curve blurs exactly the conditioning this page performs.</li>
<li><strong>Carbohydrate on board is an announcement, not a measurement.</strong>
For people who announce little it is close to meaningless; the state test was
re-run on heavy announcers alone and the result held, which is the only reason
it is quoted here.</li>
<li><strong>A negative result about named states is not a negative result about
states.</strong> It says the three labels available in this data do not carry
the tail. A state we cannot observe — absorption in progress, a failing site,
sleep — is not excluded by any of it.</li>
</ul>
</div>
</section>

__NAV__

</div>
"""


def build() -> Path:
    return page.build(BODY.replace("__NAV__", page.nav("conditioning")),
                      FILENAME, TITLE)


if __name__ == "__main__":
    build()
